### ISSUE TITLE
DMG GUI looks weird

### ISSUE THREAD

**Issue by hansvdam** [sindresorhus/create-dmg#10]
My dmg-UI has some pictures with labels ".background" and ".VolumeIcon.icns" projected below the other ones. I just ran 'create-dmg "fixture.app"' to create fixture-0.0.1.dmg in the project itself. This also happens to my own app. Any idea why?
<img width="662" alt="screen shot 2017-05-09 at 20 55 34" src="https://cloud.githubusercontent.com/assets/2060172/25867460/e26e1316-34f9-11e7-94ec-fcad67a7017c.png">
Thanks,
Hans

**Comment by sindresorhus** [comment]
You have "Show hidden files" turned on in Finder. Try pressing Cmd+Shift+.

There's a hack to hide them, but that introduces a scrollbar, so not sure which path to take: https://github.com/LinusU/node-appdmg#hidden-files Right now I'm optimizing for end-users that doesn't show hidden files.

**Comment by hansvdam** [comment]
Ah thanks! Well I guess you're right that it's only a small part of the population that has hidden files on. And the thing still works in that case anyway. Good work for the dmg-creator! I strongly agree that no one needs a lot of options for something that has only has one linear purpose.

**Comment by sindresorhus** [comment]
Closing as I prefer the current solution. It's more user-friendly.
