### ISSUE TITLE
Created DMGs don't work on Mac OS Yosemite

### ISSUE THREAD

**Issue by whmountains** [sindresorhus/create-dmg#11]
First of all, thanks for making `create-dmg`!  I'm using as part of my build pipeline.

Recently I got a support call from a customer who was getting errors when trying to open the DMG.  DiskImageMounter claimed that the disk image was corrupt.  They were using a MacBook Pro with Mac OS Yosemite.

I was able to set up a remote connection over TeamViewer and used the `shasum` command in Terminal to check the integrity of the file.  It matches exactly with the file on my mac yet it won't open on their computer.  I thought it must be a fluke, but they get the same error on two different laptops, both running Yosemite.

Do you know of anything that could be causing this?  Are you using some new, cutting-edge DMG format or something?

**Comment by sindresorhus** [comment]
> Do you know of anything that could be causing this? Are you using some new, cutting-edge DMG format or something?

Yes, from the readme:

> The DMG requires macOS 10.11 or later

And no, sorry, I'm not going to change this or add an option to change it. I don't support Yosemite in anything I do, and neither should anyone really. macOS updates are free.

---

If you really have to support Yosemite, you could change [this](https://github.com/sindresorhus/create-dmg/blob/4933b339afcfc0997bea3c230de1b171508b0eb9/cli.js#L61) locally to `UDBZ`.

**Comment by whmountains** [comment]
Thank you!  It never occurred to me to check the README.  (I'm laughing out loud at my stupidity.)

What is the benefit of the newer format?  Better compression ratio, I'm guessing?

**Comment by sindresorhus** [comment]
Yes, better compression.

**Comment by vasyl-shumskyi** [comment]
@whmountains just curious what was your last decision regarding this? And are you OK with `UDBZ` dmg? Thanks!

**Comment by whmountains** [comment]
Yes, UDBZ works fine on Yosemite.

I'm using create-dmg with my electron app.  Electron provides a nice compatibility layer, and it didn't make sense to drop Yosemite support for a small thing like DMG support.  My decision would likely have been different if I were bundling a native mac app.

I wish @sindresorhus would add a command line flag to change compression format but I'm not getting my hopes up.  For now I'm happy to stick with my modified version of create-dmg.  "If it aint broke don't fix it", right?

**Comment by vasyl-shumskyi** [comment]
Thanks for such quick response @whmountains. It also works on Mavericks. See #19 

I've got following issue on my Mac with  Sierra 10.12.6 which was confirmed by a user using Mavericks 10.9.4

 Double clicking on the app without drag'n'drop it to Applications folder first - launch it a way slower and sometimes with errors:

![screen shot 2018-02-12 at 14 29 50](https://user-images.githubusercontent.com/2331802/36111379-9af8ef2c-102e-11e8-8cb5-29178ff8d2c8.png)

![image 2](https://user-images.githubusercontent.com/2331802/36111438-cc359a7c-102e-11e8-91a3-613c13f5e3cc.png)

So its safer for me to go with old good zip for now...

**Comment by vasyl-shumskyi** [comment]
[Desktop macOS Version Market Share Worldwide - January 2018
](http://gs.statcounter.com/macos-version-market-share/desktop/worldwide)

**Comment by whmountains** [comment]
I think that error may be highlighting a bug in your app.  Are you waiting for the `ready` event before creating your first `browserWindow`?

Your app looks interesting.  Where can I try it out?

**Comment by sindresorhus** [comment]
@vasyl-shumskyi Don't let users launch your Electron app from a DMG. It can cause other problems too. See https://github.com/sindresorhus/electron-util#enforcemacosapplocation

**Comment by vasyl-shumskyi** [comment]
@whmountains agreed. For me it looks like a bug as well. I should make big refactoring of the app. Since its my first try not only in Electron / Node.JS world but on Programming as well.

> Your app looks interesting. Where can I try it out?
You can get more info about the app here https://qiplex.com/software/organize-my-files/ 
There is only paid $3+ version on the website.. Sorry. Please drop me an email at hello@domain-name and I share free version with you.

@sindresorhus thanks for pointing out that valuable info. `electron-util` seems to be very useful. Added project to favs.
