### ISSUE TITLE
[Feature request] Output dir

### ISSUE THREAD

**Issue by MehediH** [sindresorhus/create-dmg#12]
Hey, 

This is a great tool but it would be awesome if you could let us choose the output directory rather than creating the .dmg on the current directory.

Thanks!

**Comment by vasyl-shumskyi** [comment]
+1

**Comment by trevordmiller** [comment]
It outputs to the current directory, so as a workaround I'm using `cd {output path} && create-dmg {app path} && cd {starting path}`. For example: `cd releases && create-dmg '../dist/mac/Foo.app' && cd ..`.

**Comment by vasyl-shumskyi** [comment]
Same here. Just using `mv`

`create-dmg 'dist/mac/Foo.app'` && `mv Foo.app.dmg releases`
