### ISSUE TITLE
Footer not displaying

### ISSUE THREAD

**Issue by vasyl-shumskyi** [sindresorhus/create-dmg#14]
Looks like footer is not displaying on Sierra with
└── create-dmg@1.3.0

![create-dmg](https://raw.githubusercontent.com/sindresorhus/create-dmg/master/screenshot-dmg.png)

**Comment by sindresorhus** [comment]
What footer?

**Comment by vasyl-shumskyi** [comment]
This one --> 

<img width="1017" alt="screen shot 2017-06-30 at 13 49 04" src="https://user-images.githubusercontent.com/2331802/27732661-f47eeea8-5d9a-11e7-9c93-438445095a4a.png">

**Comment by sindresorhus** [comment]
Does it display on any DMG? I think this is just a change to the macOS UI in Sierra. I'm personally glad the footer is gone. It IMHO looks much better without.
