### ISSUE TITLE
Doesn't work on OSX 10.9 (Mavericks)

### ISSUE THREAD

**Issue by vasyl-shumskyi** [sindresorhus/create-dmg#19]
Hello,

Looks like create-dmg doesn't work on Mavericks. Even Mavericks is like 5 years old OS, but there are some people who still using it. 

http://gs.statcounter.com/macos-version-market-share/desktop/worldwide

One guy wasn't able to open dmg image on Mavericks 10.9.4

He sent me the following screenshot: 

![image 1](https://user-images.githubusercontent.com/2331802/36094687-e09702ee-0ff7-11e8-91c7-302eda363393.png)

I will be very grateful if you can fix it.

**Comment by sindresorhus** [comment]
This is already documented in the readme:

> The DMG requires macOS 10.11 or later

**Comment by vasyl-shumskyi** [comment]
Thanks for the info @sindresorhus 

Will changing `ULFO` to `UBDZ` will support Mavericks? 

Like you mentioned in similar Yosemite issue
https://github.com/sindresorhus/create-dmg/issues/11#issuecomment-301828156

**Comment by sindresorhus** [comment]
Yes

**Comment by vasyl-shumskyi** [comment]
Thanks @sindresorhus Appreciate your help.

Just tested both formats on Sierra. Comparing to `ULFO`, `UDBZ` is slower than dial-up :)

**Comment by z-ax** [comment]
Don't get why is it closed. As see in sources, `format: 'ULFO'` but according to `man hdiutil` it supported by only 10.11+, what is the reason?

```
                      UDCO - UDIF ADC-compressed image
                      UDZO - UDIF zlib-compressed image
                      ULFO - UDIF lzfse-compressed image (OS X 10.11+ only)
                      UDBZ - UDIF bzip2-compressed image (Mac OS X 10.4+ only)
```
