### ISSUE TITLE
About README Demo Gif，IDE ！

### ISSUE THREAD

**Issue by Suremotoo** [sindresorhus/create-dmg#20]
![image](https://user-images.githubusercontent.com/26423989/38067148-c3a16df0-333d-11e8-8616-834cc20bc3fb.png)
 it's ，beautiful！what is it？

**Comment by sindresorhus** [comment]
The terminal is Hyper. See: https://github.com/sindresorhus/ama/issues/458

**Comment by Suremotoo** [comment]
Oh, Thanks!
