### ISSUE TITLE
Codesign identity as optional parameter

### ISSUE THREAD

**Issue by dminta** [sindresorhus/create-dmg#23]
For two Developer ID distribution certificates installed on my machine (both from different teams) I receive following warning:

```
Code signing failed. The DMG is fine, just not code signed.
Developer ID Application: ambiguous (matches "Developer ID Application: OrganizationA (XXXXXXXXXX)" and "Developer ID Application: OrganizationB (YYYYYYYYY)" in /Users/user/Library/Keychains/login.keychain-db)
XXXXXXXXXX
```
It would be nice to have an optional parameter to resolve this issue, for example:

`
--identity "Developer ID Application: OrganizationB (YYYYYYYYY)"
`

**Comment by sindresorhus** [comment]
Sure. PR welcome.
