### ISSUE TITLE
Option to not sign (or throw different error code)

### ISSUE THREAD

**Issue by fcastilloec** [sindresorhus/create-dmg#24]
When using this CLI module inside a script, there's no way to differentiate between an error when creating a DMG or simply this warning message **Code signing failed. The DMG is fine, just not code signed.**
I would like to have an option to not sign the DMG. I understand that this module is trying to be as simply as possible, so as an alternative, would it be possible to not throw any error for that warning? or just throw a different error code? For example, `process.exit(2)` for the case described above, so it's easy to know what the error is about and handle it.

It's a good practice for CLI apps to throw different error codes, depending on the errors themsleves, and document what each one represent.

**Comment by sindresorhus** [comment]
I'm ok with a different error code.
