### ISSUE TITLE
Upcoming OS X signing changes

### ISSUE THREAD

**Issue by getaclue** [sindresorhus/create-dmg#25]
Hey guys,

First, thank you @sindresorhus for making this wonderful tool. I love using it.

Everything was working fine and dandy for my Mac OS X application.
Code signing started to fail and I started to look into it.

As you can see in:
![img](https://d.pr/i/0fRWLL+)

It looks like we need to sign the dmg using the `Developer ID Installer` profile and not a `Developer ID Application` profile. I say it looks like because I am still debugging.

![img](https://d.pr/i/Dz3EfA+)

# context:
- using fastlane tools to generate `.app` via `gem 'fastlane-plugin-dmg'` which does:
```rb
lane :build_mac_dmg do
    version_num = get_info_plist_value(path: "./App/Info.plist", key: "CFBundleShortVersionString")
    # this is -1 b/c after successful build we incremented this number (in Xcode)
    build_num = get_info_plist_value(path: "./App/Info.plist", key: "CFBundleVersion").to_i - 1

    _release_location = "releases/#{version_num}/#{build_num}"
    destination_dir = File.join(File.dirname(File.expand_path('.')), _release_location)
    _dmg_location = File.join(destination_dir, "App.dmg")

    remove_zip = File.join(destination_dir, "*.zip")
    remove_app = File.join(destination_dir, "*.app")

    sh "rm #{remove_zip}"

    dmg(
      path: _release_location, 
      output_path: _dmg_location,
      volume_name: "App"
    )

    sh "rm -rf #{remove_app}"
  end
```
- then we just cd into `_release_location` and run `create-dmg App.app`
- the `dmg` is created fine but is not signed anymore

Tried to do it manually to figure it out the `cli.js`:

```bs
####### Command 1
$ codesign --force --sign "Developer ID Application: Alex Kluew (6E9FSS8PG2)" App.dmg
####### Result
App.dmg: A timestamp was expected but was not found.
####### Command 2
$ spctl -a -t open --context context:primary-signature -v App.dmg
####### Result
App.dmg: rejected
source=no usable signature
```

At the moment not sure where to proceed.

## Conclusion
Mainly posting here to see if anyone else is struggling or it is just me?
Kind of looks like they changed something in the Mac signing process but I am not intimate with this process.

They also added the notarization process... so this may be an issue in the future as well...

Thanks for any help.

Cheers,
Alex

## Related
- https://help.apple.com/xcode/mac/current/#/dev033e997ca
- https://help.apple.com/xcode/mac/current/#/deve51ce7c3d
- https://help.apple.com/xcode/mac/current/#/dev88332a81e

**Comment by sindresorhus** [comment]
A DMG is not an ["installer package"](https://en.m.wikipedia.org/wiki/Installer_(macOS)) in this sense.

> Disk images should only be signed with your Developer ID Application identity.
> \-https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG18

**Comment by getaclue** [comment]
ok @sindresorhus thank you for that information! it was helpful!

ended up adding `--timestamp=none` to the original command. 
Like this:
```
codesign --sign "Developer ID Application" --timestamp=none App.dmg
```
and we are back in business

reference = https://stackoverflow.com/questions/15232165/codesign-not-working-timestamp-service-not-available

PS. they say it is network errors - but I tried on various networks in my area and it did not work. Not home. Not public. Nothing.

**Comment by getaclue** [comment]
so I'll close this for now since it appears to be a me problem... I'll just modify my own `cli.js` for now until I figure out a better solution
