### ISSUE TITLE
Custom DMG icon is gone after uploading and downloading

### ISSUE THREAD

**Issue by zachgibson** [sindresorhus/create-dmg#42]
When I create my Disk Image it has the custom icon, but then if I upload it to S3 or GitHub and download it, the icon is missing. It might be something I’m doing, but have you ever seen this happen?

Left is original, right is after downloading from GitHub.
![image](https://user-images.githubusercontent.com/10658888/68090307-ec24c580-fe37-11e9-8f08-40c542621a8a.png)

**Comment by nrlquaker** [comment]
I got the same issue.

**Comment by nrlquaker** [comment]
Checked hashes with `shasum -a 256` and size with `stat -f%z`. Both are the same. But `Finder` reports different file sizes. For downloaded file `Finder` displays size the same as `stat -f%z`. But original file is 1mb larger.

**Comment by rahbari** [comment]
I had this problem too, after zipping the dmg and opening it in windows I found out that there is __MACOSX folder beside the dmg file which probably contains the icon. So distributing zip instead of dmg itself resolves the problem although it's not ideal.

**Comment by sindresorhus** [comment]
// @manrueda

**Comment by michaelsbradleyjr** [comment]
I'm experiencing this behavior as well.

**Comment by jimmyed2000** [comment]
Here is the answer
Compress the DMG before you upload it. There is an invisible side-car file for the DMG (makes no sense to me why). When you compress the DMG the sidecar file is included. When someone downloads the zip file OS X automatically displays the contents of the zip file - the DMG with its icon.

**Comment by sindresorhus** [comment]
As of v7, it only adds a icon to the mounted DMG, not the DMG file, so this is no longer relevant. https://github.com/sindresorhus/create-dmg/releases/tag/v7.0.0
