### ISSUE TITLE
DMG Icon is blurry

### ISSUE THREAD

**Issue by zachgibson** [sindresorhus/create-dmg#43]
My custom DMG icon is blurry for some versions. I’ve added all the right resolution icons in my `Assets.xcassets` AppIcon. If I mount the DMG, the icon looks perfect.

![image](https://user-images.githubusercontent.com/10658888/68090408-001cf700-fe39-11e9-9c49-4bb65242a74e.png)
![image](https://user-images.githubusercontent.com/10658888/68090355-6fdeb200-fe38-11e9-89c6-1c9ca7b37892.png)

**Comment by sindresorhus** [comment]
// @manrueda

**Comment by manrueda** [comment]
Hi @zachgibson, can you provide an example icon set with which I can reproduce the error, thanks!

**Comment by sindresorhus** [comment]
@zachgibson Ping

**Comment by Cykelero** [comment]
I was looking at this issue, running create-dmg on a private personal project.

Looks like in the case of that app:
- the `AppIcon.icns` file in the app bundle only contains sizes up to 256x256
- the `Assets.car` file in the app bundle contains all sizes, including the biggest, 1024x1024

If this is how Xcode builds apps now, this would explain why create-dmg—which reads the `AppIcon.icns` file as a source—doesn't generate larger sizes.
