### ISSUE TITLE
More verbose errors would be useful

### ISSUE THREAD

**Issue by cbenhagen** [sindresorhus/create-dmg#44]
The following error message is quite minimalistic :P
```
✖
```

**Comment by cbenhagen** [comment]
In my case it was missing imagemagick:
```
brew install graphicsmagick imagemagick
```

Am better error message would have helped to fix this though.

**Comment by sindresorhus** [comment]
`imagemagick` is optional and we already have a check for it: https://github.com/sindresorhus/create-dmg/blob/4f80ea2d80b145d88b32597eaefdf7e8adb1085e/compose-icon.js#L38-L49

Can you replace https://github.com/sindresorhus/create-dmg/blob/4f80ea2d80b145d88b32597eaefdf7e8adb1085e/cli.js#L169 with `throw error;` and share the stack trace?
