### ISSUE TITLE
Getting error "x" when running and nothing happens

### ISSUE THREAD

**Issue by dbklabs** [sindresorhus/create-dmg#45]
Title says it all
<img width="581" alt="Screen Shot 2019-11-20 at 5 31 25 PM" src="https://user-images.githubusercontent.com/48579572/69292700-954f1800-0bbb-11ea-8fc4-639e936ee9e2.png">

**Comment by sindresorhus** [comment]
Duplicate of #44

**Comment by cbenhagen** [comment]
In my case it was missing imagemagick:
```
brew install graphicsmagick imagemagick
```

Am better error message would have helped to fix this though.
