### ISSUE TITLE
hdiutil: couldn't un mount "disk2" - Resource busy

### ISSUE THREAD

**Issue by m0o066** [sindresorhus/create-dmg#46]
OS: macOS Catalina `10.15.2`
node: `12.14.0`
npm: `6.13.4`
create-dmg: `4.2.0`

---

Hi. I'm using `create-dmg` to create dmg from my app file:

```
create-dmg ../dist/mac/MyApp.app ../dist --overwrite
```

But always got the following error output

```
✖ Building the DMG failed. Error: Command failed: hdiutil detach /Volumes/MyApp
hdiutil: couldn't unmount "disk2" - Resource busy

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@1.22.2 installer:macos: `create-dmg ../dist/mac/MyApp.app ../dist --overwrite`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myapp@1.22.2 installer:macos script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
...
```

When this error happens, Disk Utility always shows a mounted image as shown below:

<img width="926" alt="disk" src="https://user-images.githubusercontent.com/165961/72247964-03024800-3631-11ea-8c7e-9e14d04faed3.png">

**Comment by m0o066** [comment]
Hmmm, I think this is not the right place to post this issue since `create-dmg` uses `appdmg` to generate the dmg file, and this error is actually originated from `appdmg`. I'll close this issue for now and try to post PR on `appdmg` side.

**Comment by tomershvueli** [comment]
@m0o066 I'm seeing this same issue appear for me as well. Were you ever able to get this resolved?

**Comment by tomershvueli** [comment]
Following up from my comment a few days ago: this error behavior is inconsistent and after playing around with it a bit it's working again ¯\_(ツ)_/¯
