### ISSUE TITLE
Command return X only

### ISSUE THREAD

**Issue by malavagile** [sindresorhus/create-dmg#48]
Hello Team,

I have installed this script through the terminal using HomeBrew. Now I tried to create DMG and get the only X in response. Have a look at the attached screenshot here. 

Can you help me in identifying what exactly I am doing wrong here?

![Screenshot 2020-03-05 at 1 17 49 PM](https://user-images.githubusercontent.com/10988932/75959350-11a80580-5ee4-11ea-8e2b-8431da1dbe08.png)

Thanks,
Malav Soni

**Comment by sindresorhus** [comment]
Installing through Homebrew is not officially supported. The missing error issue was fixed in the latest version. Install using the install instructions in the readme.

**Comment by malavagile** [comment]
> Installing through Homebrew is not officially supported. The missing error issue was fixed in the latest version. Install using the install instructions in the readme.

But I haven't installed that using HomeBrew.

I simply follow the commands from here. 
https://github.com/sindresorhus/create-dmg/blob/master/readme.md

**Comment by rkbhochalya** [comment]
@sindresorhus I'm getting same ✖error using v5.0.0 installed globally through yarn. I also have  GraphicsMagick installed through Homebrew. My app is in alpha and doesn't have an icon yet. Maybe thats why I'm getting this error?
