### ISSUE TITLE
Code signing failed

### ISSUE THREAD

**Issue by armoucar** [sindresorhus/create-dmg#5]
Hey, I have an electron app which I package using `electron-packager`.

I'm trying to use create-dmg on it and it fails.

```
$ create-dmg Proton.app
✖ Code signing failed. The DMG is fine, just not code signed.
error: The specified item could not be found in the keychain.
```

What should be in my keychain? Thanks

**Comment by sindresorhus** [comment]
You need the correct certificates. Did you already sign the app itself? If not, you need to get that set up first. This should *just work* then.
