### ISSUE TITLE
dmg-title option don't work

### ISSUE THREAD

**Issue by YGAS** [sindresorhus/create-dmg#52]
--dmg-title=<value>.
I have added the option. But no effects.

**Comment by sindresorhus** [comment]
What is the exact command you used?

// @sartbimpson

**Comment by YGAS** [comment]
create-dmg ―dmg-title=xxx.dmg xxx.app

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Sindre Sorhus <notifications@github.com>
发送时间: Wednesday, April 29, 2020 10:37:46 PM
收件人: sindresorhus/create-dmg <create-dmg@noreply.github.com>
抄送: YGAS <ycl310397039@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [sindresorhus/create-dmg] dmg-title option don't work (#52)


What is the exact command you used?

// @sartbimpson<https://github.com/sartbimpson>

―

**Comment by sartbimpson** [comment]
@YGAS, `--dmg-title` will change the title of the disk image as viewed in Finder, not the file name of the exported image from `create-dmg`

@sindresorhus, the command works (application name is still "Hammerspoon" but it is changed by `create-dmg` to "Live Enhancement Suite")

![image](https://user-images.githubusercontent.com/63189531/80612810-1c04fc80-8a5a-11ea-9a71-709bb0c4e50d.png)

**Comment by YGAS** [comment]
I got it. Thank you for your help.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sart bimpson <notifications@github.com>
发送时间: Wednesday, April 29, 2020 11:14:48 PM
收件人: sindresorhus/create-dmg <create-dmg@noreply.github.com>
抄送: YGAS <ycl310397039@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [sindresorhus/create-dmg] dmg-title option don't work (#52)


@YGAS<https://github.com/YGAS>, --dmg-title will change the title of the disk image as viewed in Finder, not the file name of the exported image from create-dmg

@sindresorhus<https://github.com/sindresorhus>, the command works (application name is still "Hammerspoon" but it is changed by create-dmg' s --dmg-title to "Live Enhancement Suite")

[image]<https://user-images.githubusercontent.com/63189531/80612810-1c04fc80-8a5a-11ea-9a71-709bb0c4e50d.png>

―
