### ISSUE TITLE
Error: data.title is required

### ISSUE THREAD

**Issue by juniordiscart** [sindresorhus/create-dmg#54]
Whenever I attempt to create a dmg with the simplest command `create-dmg Launcher.app` it throws the error that data.title is required.

When specifying the `--dmg-title=Launcher.dmg` option, it will work, but creates a dmg file that does not have the specified name, but rather `undefined undefined.dmg`.

**Comment by sindresorhus** [comment]
Does the `Info.plist` have a `CFBundleDisplayName` or `CFBundleName` key? `create-dmg` assumes it has a name.

**Comment by juniordiscart** [comment]
That seems to be the problem indeed. The app I'm trying to create an installer for is a third-party launcher application, which doesn't have these values set. So I wasn't aware of these values.

Thanks for the quick reply!

**Comment by sindresorhus** [comment]
I've improved the error message: https://github.com/sindresorhus/create-dmg/commit/7a1ea2ba131e676b6b357f208d1be7250cbee043
