### ISSUE TITLE
Created DMG name?

### ISSUE THREAD

**Issue by IgorAnohin** [sindresorhus/create-dmg#55]
Hello!

What do you think about the new option to write generated `.dmg` filename to console?
For example:
```shell
✔ DMG mydmg.dmg created
```
instead of 
```shell
✔ DMG created
```

It might be very useful and more informative.
If you agree with this, I can try to create PR :)

**Comment by sindresorhus** [comment]
In what way is it useful?

**Comment by IgorAnohin** [comment]
It may help to get the name of generated .dmg from other scripts.
I use your util in `.sh` script. Unfortunately, I have no info about the name of the output file.

Do you know any sideway how to get it without parsing the file `Info.plist`?

**Comment by IgorAnohin** [comment]
Why am I use your util in `.sh` script?

I create `.dmg` file with your util and notarize generated file. I want to automatize this process by `.sh` script.

**Comment by sindresorhus** [comment]
Thanks, that makes sense.

**Comment by sindresorhus** [comment]
Although, you could just glob for `*.dmg`. That would be better than trying to parse a random unstable output.
