### ISSUE TITLE
Build version not matching version in package.json

### ISSUE THREAD

**Issue by aubreypwd** [sindresorhus/create-dmg#60]
When I bump the version in `package*.json` and I run, e.g.

```
./node_modules/.bin/create-dmg './build/Twitter-darwin-x64/Twitter.app' --overwrite --dmg-title='Twitter' --identity='Aubrey Portwood' ./dist/"
```

The version in `dist/` is always `1.0.0`.

![image](https://user-images.githubusercontent.com/1753298/97086232-3a018300-15df-11eb-84e4-14509f587c01.png)

**Comment by fcastilloec** [comment]
Did you rebuild it with `electron-packager` after updating the version? This module doesn't use the info on your `package.json` directly, it uses the info of the `package.json` inside of your packaged app

**Comment by aubreypwd** [comment]
I did not, I have used it successfully to package a folder with a .app in it that get's built by `nativefier`. I will look into this more and report back if I can.
