### ISSUE TITLE
Support for APFS and LZMA compression

### ISSUE THREAD

**Issue by zorgiepoo** [sindresorhus/create-dmg#79]
I'm creating this to discuss support for creating APFS disk images (which requires 10.13+) and disk images using "ULMO" (or lzma compressed) format (which requires 10.15+). Both of these are 'relatively' modern features/enhancements to dmgs.

Given that this tool is "opinionated",  if the app minimum system requirement is >= 10.13, I think it always makes sense to just opt into creating APFS disk images over HFS+ ones.

For the ULMO format it's not always really clear cut if the developer wants fast decompression (lzfse) or significantly reduced file compression (lzma). (In some cases for my relatively-small apps I find the decompression speed difference to be less noticeable while the compression file size savings to be more significant for example; lzma is much better than bzip2). In this case, I'd perhaps suggest an "extra-compression" or "heavy-compression" option which uses ULMO if the minimum system requirement is >= 10.15, otherwise use UDBZ (bzip2) (or perhaps don't support UDBZ at all).

Either way, it's not possible to integrate these modern-parity enhancements right now. I've added pull requests to the upstream node-appdmg project for adding them there first (including more motivational details). I created this to open a discussion as I'm not sure whether these are wanted here.

https://github.com/LinusU/node-appdmg/pull/220
https://github.com/LinusU/node-appdmg/pull/221

**Comment by sindresorhus** [comment]
I agree with defaulting to APFS and ULMO when macOS 10.15+. I don't see the need to have options for either.

**Comment by sindresorhus** [comment]
Sounds like ULFO is indeed the best default though. I'm not sure I want to introduce any more flags. I specifically made this package as minimal as possible so users don't have to make difficult technical decisions.

From a users perspective it's also not clear what to prioritise. Should I prioritise users with a fast internet connection or a fast computer.
