### ISSUE TITLE
macOS: Enable create-dmg/AppleScript permissions for CI (e.g. TeamCity)

### ISSUE THREAD

**Issue by kafeg** [sindresorhus/create-dmg#85]
Hello all. This is just for keep note about how to give all required permissions to the create-dmg to be executed on macOS on CI devices.

What we need to do is disable SIP and then manually add the permissions to the macOS DB.

Here what the permissions must be added: https://support.circleci.com/hc/en-us/articles/360057033612-Enabling-AppleScript-Support-on-macOS
And here the source code sample: https://circleci.com/developer/orbs/orb/circleci/macos#commands-add-permission

**Comment by alien2108** [comment]
You can fix that by giving osascript System Events permission!

System Preferences/Privacy & Security/Automation/osascript -> Enable "System Events"

**Comment by Yongle-Fu** [comment]
same issue

System Preferences/Privacy & Security/Automation/osascript -> Finder is opened

MacOS 14.4.1

Running AppleScript to make Finder stuff pretty: /usr/bin/osascript "/var/folders/sh/vmbfsw6x5fv2mn91h60r1jj00000gn/T/createdmg.tmp.XXXXXXXXXX.TKl9RLPvcm" "dmg.CoVa2C"
/var/folders/sh/vmbfsw6x5fv2mn91h60r1jj00000gn/T/createdmg.tmp.XXXXXXXXXX.TKl9RLPvcm:817:870: execution error: “Finder”遇到一个错误：不能将“item "Applications.app" of disk "dmg.CoVa2C"”设置为“{200, 190}”。 (-10006)
Failed running AppleScript
Unmounting disk image...
"disk12" ejected.
