### ISSUE TITLE
i keep getting Not enough arguments

### ISSUE THREAD

**Issue by tf7software** [sindresorhus/create-dmg#90]
(base) Unknown:Applications henry$ create-dmg Packet\ King.app
Not enough arguments. Run 'create-dmg --help' for help.
(base) Unknown:Applications henry$

**Comment by sindresorhus** [comment]
It looks like you're using a different project with the same name.

**Comment by pzhlkj6612** [comment]
It appears to be the [create-dmg/create-dmg](https://github.com/create-dmg/create-dmg) project.
