### ISSUE TITLE
DeprecationWarning: The `util.isDate` API is deprecated.

### ISSUE THREAD

**Issue by hyrulelinks** [sindresorhus/create-dmg#91]
There is a warning message that has never appeared before, and it seems to be an API deprecation

```
❯ create-dmg fly.app
⠦ Copying files(node:37860) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✖ No suitable code signing identity found
```
Shall I reinstall creata-dmg?

Thx
@sindresorhus

**Comment by sindresorhus** [comment]
It is not coming from `create-dmg`. Must be a sub-dependency. You should open an issue on that sub-dependency instead.
